export const STATES = [
	{ value: 'CT', label: 'Connecticut' },
	{ value: 'ME', label: 'Maine' },
	{ value: 'MA', label: 'Massachusetts' },
	{ value: 'NH', label: 'New Hampshire' },
	{ value: 'RI', label: 'Rhode Island' },
	{ value: 'VT', label: 'Vermont' },
	{ value: 'NY', label: 'New York' },
	{ value: 'NJ', label: 'New Jersey' },
	{ value: 'PA', label: 'Pennsylvania' },
	{ value: 'DE', label: 'Delaware' },
	{ value: 'MD', label: 'Maryland' },
	{ value: 'DC', label: 'District of Columbia' },
	{ value: 'VA', label: 'Virginia' },
	{ value: 'WV', label: 'West Virginia' },
	{ value: 'NC', label: 'North Carolina' },
	{ value: 'SC', label: 'South Carolina' },
	{ value: 'GA', label: 'Georgia' },
	{ value: 'FL', label: 'Florida' },
	{ value: 'AL', label: 'Alabama' },
	{ value: 'MS', label: 'Mississippi' },
	{ value: 'LA', label: 'Louisiana' },
	{ value: 'TX', label: 'Texas' },
	{ value: 'OK', label: 'Oklahoma' },
	{ value: 'KS', label: 'Kansas' },
	{ value: 'NE', label: 'Nebraska' },
	{ value: 'SD', label: 'South Dakota' },
	{ value: 'IA', label: 'Iowa' },
	{ value: 'MN', label: 'Minnesota' },
	{ value: 'WI', label: 'Wisconsin' },
	{ value: 'IL', label: 'Illinois' },
	{ value: 'IN', label: 'Indiana' },
	{ value: 'OH', label: 'Ohio' },
	{ value: 'MI', label: 'Michigan' },
	{ value: 'RI', label: 'Rhode Island' },
	{ value: 'MA', label: 'Massachusetts' },
	{ value: 'CT', label: 'Connecticut' },
	{ value: 'VT', label: 'Vermont' },
	{ value: 'NH', label: 'New Hampshire' },
	{ value: 'ME', label: 'Maine' },
	{ value: 'PR', label: 'Puerto Rico' },
	{ value: 'VI', label: 'Virgin Islands' },
	{ value: 'GU', label: 'Guam' },
	{ value: 'AS', label: 'American Samoa' },
	{ value: 'MP', label: 'Northern Mariana Islands' },
	{ value: 'MH', label: 'Marshall Islands' },
	{ value: 'FM', label: 'Micronesia' },
	{ value: 'PW', label: 'Palau' },
	{ value: 'NR', label: 'Nauru' }
]
